language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t vrabota/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true vrabota/docker-react npm run test